--- #YAML:1.0
name:               Linux-SysInfo
version:            0.11
abstract:           Perl interface to the sysinfo(2) Linux system call.
author:
    - Vincent Pit <perl@profvince.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
    Test::More:           0
requires:
    Exporter:  0
    perl:      5.006
    XSLoader:  0
resources:
    bugtracker:  http://rt.cpan.org/NoAuth/ReportBug.html?Queue=Linux-SysInfo
    homepage:    http://search.cpan.org/dist/Linux-SysInfo/
    license:     http://dev.perl.org/licenses/
    repository:  http://git.profvince.com/perl/modules/Linux-SysInfo.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
